# Generated by Django 4.2.7 on 2023-11-23 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resident', '0011_delete_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_count', models.IntegerField()),
                ('begin_datetime', models.DateTimeField(null=True, unique=True)),
                ('end_datetime', models.DateTimeField(null=True, unique=True)),
                ('status', models.CharField(choices=[('canceled', 'отменён'), ('moderation', 'в модерации'), ('approved', 'одобрен'), ('notapproved', 'не одобрен'), ('sended', 'отправлено')], default='moderation', max_length=11)),
                ('tour_format', models.CharField(choices=[('overwiew', 'Обзорная экскурсия'), ('education', 'Образовательная экскурсия'), ('exhibition', 'Экспозиционные мероприятия'), ('buisiness', 'Бизнес-тур для инвесторов'), ('profile', 'Профильные')], max_length=11)),
                ('comment', models.CharField(blank=True, max_length=2500, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tours', to=settings.AUTH_USER_MODEL)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_tours', to=settings.AUTH_USER_MODEL)),
                ('residents', models.ManyToManyField(related_name='resident_tours', to='resident.resident')),
            ],
        ),
    ]
