# Generated by Django 4.2.7 on 2023-11-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='tour_format',
            new_name='format',
        ),
    ]
