# Generated by Django 4.2.7 on 2023-11-22 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0003_tour_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='residents',
            field=models.ManyToManyField(related_name='resident_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('canceled', 'отменён'), ('moderation', 'в модерации'), ('approved', 'одобрен'), ('notapproved', 'не одобрен')], max_length=11),
        ),
    ]
