# Generated by Django 4.2.7 on 2023-11-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_remove_resident_owner_resident_responsible_and_more'),
        ('tour', '0004_tour_residents_alter_tour_client_alter_tour_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='residents',
            field=models.ManyToManyField(related_name='resident_tours', to='resident.resident'),
        ),
    ]
