# Generated by Django 4.2.7 on 2023-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0005_resident_tags_alter_resident_floor'),
        ('tour', '0005_alter_tour_residents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='comment',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='resident_tours', to='resident.resident'),
        ),
    ]
