# Generated by Django 4.2.7 on 2023-11-22 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_tour_comment_alter_tour_residents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='datetime',
            new_name='begin_datetime',
        ),
        migrations.AddField(
            model_name='tour',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
