# Generated by Django 4.2.7 on 2023-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_rename_datetime_tour_begin_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('canceled', 'отменён'), ('moderation', 'в модерации'), ('approved', 'одобрен'), ('notapproved', 'не одобрен')], default='moderation', max_length=11),
        ),
    ]
