# Generated by Django 4.2.7 on 2023-11-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_alter_tour_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='guest_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
