# Generated by Django 4.2.7 on 2023-11-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_tour_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='begin_datetime',
            field=models.DateTimeField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_datetime',
            field=models.DateTimeField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('canceled', 'отменён'), ('moderation', 'в модерации'), ('approved', 'одобрен'), ('notapproved', 'не одобрен'), ('sended', 'отправлено')], default='moderation', max_length=11),
        ),
    ]
