# Generated by Django 4.2.7 on 2023-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0005_resident_tags_alter_resident_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentphotos',
            name='photo',
            field=models.ImageField(upload_to='residents/photos'),
        ),
    ]
