# Generated by Django 4.2.7 on 2023-11-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0010_cabinet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cabinet',
        ),
    ]
