# Generated by Django 4.2.7 on 2023-11-23 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resident', '0011_delete_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_number', models.CharField(max_length=3)),
                ('path', models.TextField()),
                ('color', models.TextField()),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resident.resident')),
            ],
        ),
    ]
