# Generated by Django 4.2.7 on 2023-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('guest', 'обыватель'), ('org', 'организация'), ('school', 'учебное заведение'), ('resident', 'резидент'), ('delegat', 'делегация'), ('admin', 'админ')], max_length=8),
        ),
    ]
